### PR TITLE
Update typos Honeybee_Set EnergyPlus Zone Schedules.py

### PR DESCRIPTION
**Pull request by ncatunda**

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@ncatunda, this is a great start. Thank you for fixing the spelling issues. You have forgotten to update the date of the component and you are missing the updated userobject.

Use Ladybug's export

**Comment by ncatunda** [comment]
Ok, thanks for the tips! I'll have a look on that. Just one thing, I am not able to open this link, the connection time out error is appearing for me.

**Comment by mostaphaRoudsari** [comment]
Hmm. Not sure why that is happening. You can find the component under developers tab. It looks like this:

image

You need to connect the updated component to the first input and path to where the repository is cloned on your local machine to `targetFolder`. Then set the export to True and it will generate the source and the userobject files under `src` and `userobjects` folders. Then you can push the changes to GitHub and your PR will be updated.

**Comment by mostaphaRoudsari** [comment]
@ncatunda, do you need any help with this to add the userobject? Let me know if there is anything that we can do to help you and merge the PR in.

**Comment by ncatunda** [comment]
Hi @mostaphaRoudsari! I am sorry, life changed right after I started I started this and it took me 2 weeks to get back on track, sorry about this and thanks a lot for your patience! 

I did an update now. I took also a paragraph from the last line, I hope this is ok.

**Comment by mostaphaRoudsari** [comment]
Great job! Thank you. I merged it in!

**Pull request merged**
